require: 
  - rubocop-performance
  - rubocop-rails
 
inherit_from:
  - .rubocop_todo.yml
  - https://bitbucket.org/alan_maule/junglescout-rubocop/raw/master/base_config.yaml
  - .rubocop_app_overrides.yml

# NOTE: VERY IMPORTANT
#  Without this line any exclude options in this file override the rubocop_todo instead of merging
inherit_mode:
  merge:
    - Exclude

Rails:
  Enabled: true